format_version: v1.0
configName: PIC32MZEF
folderName: uart_tutorial
frameworkPath: E:\Harmony - Copy - Copy
processor: PIC32MZ2048EFM144
projectName: uart_tutorial
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32MZ-EF_DFP\1.3.58\atdf\PIC32MZ2048EFM144.atdf
